### PR TITLE
Adding permutation calculations.

### PR DESCRIPTION
**Pull request by devanp92**
Added permutation method in basic.js as well as tests for permutation in basic.tests.js

### CODE REVIEW

**Comment by StDako** [comment]
apologies for getting to this so late -- looks good.

**Comment by devanp92** [comment]
No worries. What is the state of the project? I wanted to contribute more, however, the project looks inactive.

**Comment by StDako** [comment]
it kind of is inactive. if you're looking for small things to do in the mean time, there are several functions that don't throw errors where they should. you can find these in the documentation at http://www.numbersjs.info/

**Comment by devanp92** [comment]
Ok. I created a PR in the docs repo for the permutation. I will check out the functions without errors.

**Pull request merged**
